-- Add new fields to Question model
ALTER TABLE "Question" 
ADD COLUMN "category" TEXT NOT NULL DEFAULT 'Objective',
ADD COLUMN "subtype" TEXT NOT NULL DEFAULT 'MCQ',
ADD COLUMN "applicableSubjects" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- Add new fields to BlueprintSection model
ALTER TABLE "BlueprintSection" 
ADD COLUMN "objectiveQuestionCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "subjectiveQuestionCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "requiredSubtypes" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- Update QuestionType enum
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'ASSERTION_REASONING';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'DESCRIPTIVE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'ANALYTICAL';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'EVALUATIVE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'COMPARATIVE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'APPLICATION_BASED';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'OPINION_BASED';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'EXPLORATORY';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'CAUSE_EFFECT';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'HYPOTHETICAL';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'INTERPRETIVE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'JUSTIFICATION';

-- Create QuestionCategory enum
CREATE TYPE "QuestionCategory" AS ENUM ('OBJECTIVE', 'SUBJECTIVE'); 